# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://www.huntergerlach.com
baseurl: ""
title: Hunter Gerlach
author: Hunter Gerlach
description: Personal website
avatar: profile.png
email: hunter(at)huntergerlach.com
github: HunterGerlach
twitter: HunterGerlach
linkedin: hgerlach
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: G-246NB12NH0


# needed for travis-ci build
exclude: [vendor]
